import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/shared/theme/theme-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import RecoilContextProvider from "./recoilContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <RecoilContextProvider>{children}</RecoilContextProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
