import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/shared/theme/theme-provider";
import "./globals.css";
import ThemeButton from "@/components/shared/theme/ThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
